Repository KinsonDigital/CASL, pull requests merged in 2022-12, with the labels that each got.

#114 Update README
  README.md
Labels: good first issue, low priority, preview, 📝documentation/product

#118 🚧Update to the latest version of dotnet
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: tech debt, high priority, preview

#119 🚧Update System.IO.Abstractions library
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: dependency update, high priority, preview

#124 🚧Setup all pathing to be cross platform
  CASL.sln.DotSettings
  CASL/Devices/AudioDeviceManager.cs
  CASL/ExtensionMethods.cs
  CASL/NativeInterop/NativeDependencyManager.cs
  CASL/NativeInterop/NativeLibPathResolver.cs
  CASL/NativeInterop/NativeLibraryLoader.cs
  CASL/NativeInterop/OpenALDependencyManager.cs
  CASL/NativeInterop/Platform.cs
  CASL/Sound.cs
  Testing/CASLTests/ExtensionMethodTests.cs
  Testing/CASLTests/NativeInterop/NativeDependencyManagerTests.cs
  Testing/CASLTests/NativeInterop/NativeLibPathResolverTests.cs
  Testing/CASLTests/NativeInterop/NativeLibraryLoaderTests.cs
Labels: tech debt, high priority, preview
