Repository KinsonDigital/CASL, pull requests merged in 2023-06, with the labels that each got.

#213 🚧Remove CICD from project
  .config/dotnet-tools.json
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .nuke/parameters.json
  BuildScripts/Cleanup.ps1
  BuildScripts/PackageTestingApp.ps1
  BuildScripts/ScriptStart.ps1
  CASL.sln
Labels: ♻️cicd, high priority, preview

#197 🚧Create auto project workflows
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check-not-required.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-testing-status-check-not-required.yml
  .vscode/settings.json
Labels: ♻️cicd, high priority

#210 🚧Add rule to solution editorconfig
  .editorconfig
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check-not-required.yml
  .github/workflows/unit-testing-status-check-not-required.yml
Labels: good first issue, preview, 📝documentation/product

#216 🚧Create preview release workflow
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-pr-to-project.yml
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check-not-required.yml
  .github/workflows/preview-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-testing-status-check-not-required.yml
  .vscode/workflow.code-snippets
  CASL.sln.DotSettings
  CASL/CASL.csproj
  README.md
Labels: ♻️cicd, high priority, preview

#222 🚧Update NuGet pkg info
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check-not-required.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-testing-status-check-not-required.yml
  CASL/CASL.csproj
Labels: low priority, preview, 📝documentation/product

#226 ✨ Stop marking Sound as sealed
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/sync-issue-to-pr.yml
  CASL.sln
  CASL/Sound.cs
Labels: good first issue, high priority, preview

#229 🚧Fix badges in readme
  README.md
Labels: low priority, preview, 📝documentation/product

#230 Migrate dependency updates
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: dependency update, low priority, preview

#233 🚀Preview Release
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/sync-issue-to-pr.yml
  .vscode/extensions.json
  .vscode/settings.json
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.14.md
Labels: 🚀Preview Release
