Repository KinsonDigital/CASL, pull requests merged in 2023-05, with the labels that each got.

#171 🚧Create renovate config
  renovate.json
Labels: medium priority, preview, ⚙️config

#191 🚧Update all nuget packages
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: dependency update, high priority, preview

#194 🚀Preview Release
  .config/dotnet-tools.json
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .nuke/parameters.json
  .vscode/release-notes.code-snippets
  .vscode/settings.json
  CASL.sln
  CASL/CASL.csproj
  CASL/VisibleInternals.cs
  Documentation/Branching.md
  Documentation/EnvironmentSetup/LinuxDevEnvSetup.md
  Documentation/EnvironmentSetup/WindowsDevEnvSetup.md
  Documentation/Images/BranchingDiagram-DarkMode-v1.1.png
  Documentation/Images/BranchingDiagram-LightMode-v1.1.png
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
  Documentation/TableOfContents.md
  LICENSE.md
  README.md
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
  code_of_conduct.md
  renovate.json
Labels: 🚀Preview Release
