Repository KinsonDigital/CASL, pull requests merged in 2023-02, with the labels that each got.

#137 🚧Update maintainer Twitter link on home page
  Documentation/Images/twitter-logo-16x16.svg
  README.md
Labels: good first issue, high priority, preview

#141 🚧Update code of conduct
  code_of_conduct.md
Labels: good first issue, preview, 📝documentation/product

#139 🚧Add contributing doc
  CASL.sln
  CONTRIBUTING.MD
Labels: good first issue, medium priority, preview

#132 🚧Update checkout actions
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
Labels: workflow, high priority, preview

#145 🚧Add badges to README
  README.md
Labels: good first issue, low priority, preview, 📝documentation/product

#149 Remove repo related docs
  CONTRIBUTING.MD
  Documentation/Branching.md
  Documentation/EnvironmentSetup/LinuxDevEnvSetup.md
  Documentation/EnvironmentSetup/WindowsDevEnvSetup.md
  Documentation/Images/BranchingDiagram-DarkMode-v1.1.png
  Documentation/Images/BranchingDiagram-LightMode-v1.1.png
  Documentation/TableOfContents.md
  code_of_conduct.md
Labels: medium priority, preview, 📝documentation/product

#150 🚧Move internal visible setup
  CASL/CASL.csproj
  CASL/VisibleInternals.cs
Labels: tech debt, low priority, preview
