Repository KinsonDigital/CASL, pull requests merged in 2023-07, with the labels that each got.

#238 🚧Improve workflows
  .github/workflows/build-pr-status-check.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
Labels: ♻️cicd, high priority, preview

#242 🚧Fix broken image link in readme
  README.md
Labels: medium priority, preview, 📝documentation/product

#241 🚧Create add to proj workflow
  .github/workflows/add-new--issue-to-project.yml
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-test-status-check.yml
  renovate.json
Labels: ♻️cicd, high priority, preview

#246 🚧Fix broken readme badge
  .github/workflows/add-new--issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/unit-test-status-check.yml
  .vscode/tasks.json
  .vscode/workflow.code-snippets
  CASL.sln
  README.md
Labels: low priority, preview, 📝documentation/product

#266 🚧Move images and release notes
  .github/workflows/add-new--issue-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
  .vscode/settings.json
  CASL/CASL.csproj
  Images/casl-logo.ico
  Images/casl-logo.png
  README.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.11.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.14.md
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.15.md
Labels: low priority, 📝documentation/product
