Repository KinsonDigital/CASL, pull requests merged in 2023-12, with the labels that each got.

#316 🚧Update to dotnet 8
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: 📦dependency update, high priority, preview

#317 🚀Preview Release (v1.0.0-preview.17)
  CASL.sln
  CASL/CASL.csproj
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.17.md
Labels: 🚀Preview Release

#319 🚧Update reusuable workflows to use preview
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, high priority, preview

#325 🚧Update infrastructure versions
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, 📦dependency update

#323 🚧Remove Assert Extensions
  Testing/CASLTests/Devices/AudioDeviceManagerTests.cs
  Testing/CASLTests/Helpers/AssertExtensions.cs
  Testing/CASLTests/NativeInterop/NativeDependencyManagerTests.cs
  Testing/CASLTests/SoundTests.cs
Labels: tech debt, low priority, preview
