Repository KinsonDigital/CASL, pull requests merged in 2025-02, with the labels that each got.

#384 🚧Update to dotnet 9
  .run/Testing (Is Interactive).run.xml
  .run/Testing (Not Interactive).run.xml
  CASL/CASL.csproj
  Testing/CASLTesting/CASLTesting.csproj
  Testing/CASLTests/CASLTests.csproj
Labels: 📦dependency-update, high-priority, preview

#387 🐛Setting BufferType.Stream for sample causes it to glitch, repeating it partially
  CASL.sln.DotSettings
  CASL/Data/Decoders/AudioDecoder.cs
  CASL/Data/Decoders/Mp3AudioDecoder.cs
  CASL/Data/Decoders/OggAudioDecoder.cs
  CASL/Data/StreamBuffer.cs
  CASL/Data/StreamBufferManager.cs
  CASL/DotnetWrappers/ITaskService.cs
  CASL/DotnetWrappers/TaskService.cs
  CASL/Factories/AudioDecoderFactory.cs
  CASL/IoC.cs
  CASL/Wrappers/IMP3StreamWrapper.cs
  CASL/Wrappers/IVorbisReaderWrapper.cs
  CASL/Wrappers/MP3StreamWrapper.cs
  CASL/Wrappers/VorbisReaderWrapper.cs
  Testing/CASLTests/Data/Mp3AudioDecoderTests.cs
  Testing/CASLTests/Data/OggAudioDecoderTests.cs
  Testing/CASLTests/Data/StreamBufferManagerTests.cs
  Testing/CASLTests/Data/StreamBufferTests.cs
  Testing/CASLTests/TestExtensions.cs
Labels: 🐛bug, high-priority, preview

#389 🚀Preview Release (v1.0.0-preview.21)
  .github/workflows/sync-bot.yml
  .vscode/settings.json
  CASL/CASL.csproj
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.21.md
  dev-tools/prev-gen-release-notes-settings.json
  dev-tools/prod-gen-release-notes-settings.json
Labels: 🚀preview-release
